Style/TrailingCommaInLiteral:
    EnforcedStyleForMultiline: comma
Style/FileName:
    Enabled: false
Style/SpecialGlobalVars:
    Enabled: false
Style/NumericPredicate:
    Enabled: false
Metrics/MethodLength:
    Enabled: false
Metrics/AbcSize:
    Enabled: false
Metrics/PerceivedComplexity:
    Enabled: false
Metrics/CyclomaticComplexity:
    Enabled: false
Metrics/ClassLength:
    Enabled: false
Metrics/BlockLength:
    Exclude:
        - 'Rakefile'
        - '**/*.rake'
        - 'spec/**/*.rb'
